# Generated by Django 5.1.7 on 2025-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('done', 'done')], default='new', max_length=31),
        ),
    ]
