# Generated by Django 5.1.7 on 2025-03-10 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BemorningHolati',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holati', models.CharField(max_length=255)),
                ('ozgarish', models.TextField()),
            ],
            options={
                'verbose_name': 'Bemor holati',
                'verbose_name_plural': 'Bemorlar holati',
            },
        ),
        migrations.CreateModel(
            name='Jinsi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1)),
            ],
            options={
                'verbose_name': 'Jinsi',
                'verbose_name_plural': 'Jinslar',
            },
        ),
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mamlakat', models.CharField(max_length=255)),
                ('hudud', models.CharField(max_length=255)),
                ('tuman', models.CharField(max_length=255)),
                ('mahalla', models.CharField(max_length=255)),
                ('kocha_nomi', models.CharField(max_length=50)),
                ('biriktirilgan_tuman', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
            },
        ),
        migrations.CreateModel(
            name='OperatsiyaBolganJoy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mamlakat', models.CharField(max_length=255)),
                ('operatsiya_bolgan_joy', models.CharField(max_length=255)),
                ('transplantatsiya_sana', models.DateField()),
                ('operatsiya_oxirlangan_sana', models.DateField()),
                ('ishlatilgan_miqdor', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Operatsiya joyi',
                'verbose_name_plural': 'Operatsiya joylari',
            },
        ),
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JSHSHIR', models.CharField(max_length=30)),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('tugilgan_sana', models.DateField()),
                ('biriktirilgan_file', models.FileField(blank=True, null=True, upload_to='biriktirilgan/%Y/%m/%d')),
                ('qoshimcha_malumotlar', models.TextField(blank=True, null=True)),
                ('arxivga_olingan_sana', models.DateTimeField(blank=True, null=True)),
                ('bemor_holati', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bemor.bemorningholati')),
                ('jinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemor.jinsi')),
                ('manzil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bemor.manzil')),
                ('operatsiya_bolgan_joy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bemor.operatsiyabolganjoy')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'constraints': [models.UniqueConstraint(fields=('ism', 'familiya', 'tugilgan_sana'), name='unique_bemor')],
            },
        ),
    ]
