# Generated by Django 5.1.7 on 2025-03-10 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BemorQoshsih',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JSHSHIR', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Bemor qoshsih',
                'verbose_name_plural': 'Bemorlar qoshsih',
            },
        ),
        migrations.RemoveField(
            model_name='bemor',
            name='JSHSHIR',
        ),
        migrations.AddField(
            model_name='operatsiyabolganjoy',
            name='transplantatsiya_operatsiyasi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bemor',
            name='bemor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bemor.bemorqoshsih'),
            preserve_default=False,
        ),
    ]
