# Generated by Django 5.1.7 on 2025-03-11 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bemorqoshish',
            options={'verbose_name': 'Bemor JSHSHIR', 'verbose_name_plural': 'Bemor JSHSHIRlar'},
        ),
        migrations.AlterField(
            model_name='bemor',
            name='arxivga_olingan_sana',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arxivga olingan sana'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='bemor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemor.bemorqoshish', verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='bemor_holati',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bemor.bemorningholati', verbose_name='Bemor holati'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='biriktirilgan_file',
            field=models.FileField(blank=True, null=True, upload_to='media/biriktirilgan/%Y/%m/%d', verbose_name='Biriktirilgan fayl'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='manzil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bemor.manzil', verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='operatsiya_bolgan_joy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bemor.operatsiyabolganjoy', verbose_name='Operatsiya bo‘lgan joy'),
        ),
        migrations.AlterField(
            model_name='bemor',
            name='qoshimcha_malumotlar',
            field=models.TextField(blank=True, null=True, verbose_name="Qo‘shimcha ma'lumotlar"),
        ),
        migrations.AlterField(
            model_name='bemorningholati',
            name='holati',
            field=models.CharField(max_length=255, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='bemorningholati',
            name='ozgarish',
            field=models.TextField(verbose_name='O‘zgarish'),
        ),
        migrations.AlterField(
            model_name='bemorqoshish',
            name='JSHSHIR',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='JSHSHIR faqat 14 ta raqamdan iborat bo‘lishi kerak!', regex='^\\d{14}$')], verbose_name='JSHSHIR'),
        ),
        migrations.AlterField(
            model_name='bemorqoshish',
            name='familiya',
            field=models.CharField(max_length=255, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='bemorqoshish',
            name='ism',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='bemorqoshish',
            name='jinsi',
            field=models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='bemorqoshish',
            name='tugilgan_sana',
            field=models.DateField(verbose_name='Tug‘ilgan sana'),
        ),
        migrations.AlterField(
            model_name='manzil',
            name='biriktirilgan_tuman',
            field=models.CharField(max_length=255, verbose_name='Biriktirilgan tuman'),
        ),
        migrations.AlterField(
            model_name='manzil',
            name='hudud',
            field=models.CharField(max_length=255, verbose_name='Hudud'),
        ),
        migrations.AlterField(
            model_name='manzil',
            name='kocha_nomi',
            field=models.CharField(max_length=50, verbose_name='Ko‘cha nomi'),
        ),
        migrations.AlterField(
            model_name='manzil',
            name='mahalla',
            field=models.CharField(max_length=255, verbose_name='Mahalla'),
        ),
        migrations.AlterField(
            model_name='manzil',
            name='mamlakat',
            field=models.CharField(max_length=255, verbose_name='Mamlakat'),
        ),
        migrations.AlterField(
            model_name='manzil',
            name='tuman',
            field=models.CharField(max_length=255, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='ishlatilgan_miqdor',
            field=models.PositiveSmallIntegerField(verbose_name='Ishlatilgan miqdor'),
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='mamlakat',
            field=models.CharField(max_length=255, verbose_name='Mamlakat'),
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='operatsiya_bolgan_joy',
            field=models.CharField(max_length=255, verbose_name='Operatsiya bo‘lgan joy'),
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='operatsiya_oxirlangan_sana',
            field=models.DateField(verbose_name='Operatsiya oxirlangan sana'),
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='transplantatsiya_operatsiyasi',
            field=models.CharField(max_length=255, verbose_name='Transplantatsiya operatsiyasi'),
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='transplantatsiya_sana',
            field=models.DateField(verbose_name='Transplantatsiya sanasi'),
        ),
    ]
