# Generated by Django 5.1.7 on 2025-03-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemor', '0002_alter_bemorqoshish_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatsiyabolganjoy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='operatsiyabolganjoy',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='mamlakat',
            field=models.CharField(choices=[('UZ', 'O‘zbekiston'), ('RU', 'Rossiya'), ('US', 'AQSh')], max_length=255, verbose_name='Mamlakat'),
        ),
        migrations.AlterField(
            model_name='operatsiyabolganjoy',
            name='transplantatsiya_operatsiyasi',
            field=models.CharField(choices=[('jigar', 'Jigar transplantatsiyasi'), ('yurak', 'Yurak transplantatsiyasi'), ('buyrak', 'Buyrak transplantatsiyasi')], max_length=255, verbose_name='Transplantatsiya operatsiyasi'),
        ),
    ]
