# Generated by Django 5.1.7 on 2025-03-10 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemor', '0002_bemorqoshsih_remove_bemor_jshshir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bemor',
            name='bemor',
        ),
        migrations.AddField(
            model_name='bemor',
            name='JSHSHIR',
            field=models.CharField(default=1, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='JSHSHIR faqat 14 ta raqamdan iborat bo‘lishi kerak!', regex='^\\d{14}$')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BemorQoshsih',
        ),
    ]
