# Generated by Django 5.1.7 on 2025-03-10 10:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemor', '0003_remove_bemor_bemor_bemor_jshshir_delete_bemorqoshsih'),
    ]

    operations = [
        migrations.CreateModel(
            name='BemorQoshsih',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JSHSHIR', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='JSHSHIR faqat 14 ta raqamdan iborat bo‘lishi kerak!', regex='^\\d{14}$')])),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('tugilgan_sana', models.DateField()),
            ],
            options={
                'verbose_name': "Bemor qo'shish",
                'verbose_name_plural': "Bemorlar qo'shish",
            },
        ),
        migrations.RemoveConstraint(
            model_name='bemor',
            name='unique_bemor',
        ),
        migrations.RemoveField(
            model_name='bemor',
            name='JSHSHIR',
        ),
        migrations.RemoveField(
            model_name='bemor',
            name='familiya',
        ),
        migrations.RemoveField(
            model_name='bemor',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='bemor',
            name='jinsi',
        ),
        migrations.RemoveField(
            model_name='bemor',
            name='tugilgan_sana',
        ),
        migrations.AddField(
            model_name='bemorqoshsih',
            name='jinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemor.jinsi'),
        ),
        migrations.AddField(
            model_name='bemor',
            name='bemor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bemor.bemorqoshsih'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='bemorqoshsih',
            constraint=models.UniqueConstraint(fields=('ism', 'familiya', 'tugilgan_sana'), name='unique_bemor'),
        ),
    ]
