# Generated by Django 5.1.7 on 2025-03-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemor', '0004_bemorqoshsih_remove_bemor_unique_bemor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemor',
            name='biriktirilgan_file',
            field=models.FileField(blank=True, null=True, upload_to='media/biriktirilgan/%Y/%m/%d'),
        ),
    ]
