# Generated by Django 5.1.7 on 2025-03-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemor', '0005_alter_bemor_biriktirilgan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jinsi',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, unique=True),
        ),
    ]
